# Generated by Django 3.1.2 on 2020-10-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='applications',
            field=models.ManyToManyField(to='core.Candidate'),
        ),
    ]
