# Generated by Django 3.1.2 on 2020-10-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201027_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='applications',
            field=models.ManyToManyField(blank=True, to='core.Candidate'),
        ),
    ]
