# Generated by Django 3.1.2 on 2020-10-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201027_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='job_description',
            field=models.CharField(default='A very good role!', max_length=2000),
            preserve_default=False,
        ),
    ]
