# Generated by Django 3.1.2 on 2020-11-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201105_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='date_deadline',
            field=models.DateField(),
        ),
    ]
