# Generated by Django 3.1.2 on 2020-11-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201106_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
